name: mental-wellness-detection
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    # Core data science libraries
    - pandas==2.0.3
    - numpy==1.24.4
    - scikit-learn==1.3.2
    - matplotlib==3.7.5
    - seaborn==0.12.2
    # Machine Learning
    - xgboost==1.7.6
    # Deep Learning
    - torch==2.1.2
    - torchvision==0.16.2
    - torchaudio==2.1.2
    - tensorflow==2.13.1
    - keras==2.13.1
    # NLP
    - nltk==3.8.1
    - spacy==3.6.1
    - transformers==4.30.2
    # Web framework
    - flask==2.3.3
    - flask-ngrok==0.0.25
    - pyngrok==6.0.0
    # Social media APIs
    - praw==7.7.1
    - tweepy==4.14.0